development:
  access_key_id: <%= ENV['WASABI_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['WASABI_SECRET'] %>

production:
  access_key_id: <%= ENV['WASABI_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['WASABI_SECRET'] %>